### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by djhurio** [AQLT/rjdqa#1]
I am not sure why, but the installation code `devtools::install_github("AQLT/rjdqa", args = "--no-multiarch")` does not work for me. It looks that `args` argument is ignored as it tries to install the i386 version. It fails as I have x64 Java.

```
*** arch - i386
Error: package or namespace load failed for 'RJDemetra':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/MLiberts/Documents/R/R-3.6.0/library/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.
```

The alternative installation code `devtools::install_github("AQLT/rjdqa", INSTALL_opts = c("--no-multiarch"))` works for me.

**Comment by AQLT** [comment]
Do you have a problem with the CRAN release? In the past I had this problem when I used an R 32-bit version with a Java version 64-bit (or the opposite). The `--no-multiarch` argument is needed if you use a portable version of Java.
I didn't understand which code works and which doesn't :-O

**Comment by djhurio** [comment]
CRAN release is installing fine for me. I do not think this is a problem with Java. It looks like a problem of `devtools::install_github`. I will try to explain.

By default `devtools::install_github` is installing a package for both architectures - namely `i386` and `x64`. I have only x64 Java on my machine, so running `devtools::install_github("AQLT/rjdqa")` will fail as it cannot compile the package for the `i386` architecture because of missing 32bit Java. This is expected.

This is a reason you have added an extra argument `args = "--no-multiarch"` which makes the built only for the main architecture. In my case it is `x64`. However it fails for some reason. Looking at the console I see the same commands as running the installation without the `args = "--no-multiarch"`. This is a reason I suspect the `args` argument is ignored by `devtools::install_github`.

Alternative way how to pass an extra arguments to the build is using the `INSTALL_opts` argument. And it works for me in this case.

So I suggest to replace the install code from `devtools::install_github("AQLT/rjdqa", args = "--no-multiarch")` to `devtools::install_github("AQLT/rjdqa", INSTALL_opts = "--no-multiarch")`.

See the printouts from the console.

**Default installation - fails.**

```
> devtools::install_github("AQLT/rjdqa")
Downloading GitHub repo AQLT/rjdqa@master
√  checking for file 'C:\Users\MLiberts\AppData\Local\Temp\RtmpMlZozK\remotes133c5cad401e\AQLT-rjdqa-89659e9/DESCRIPTION' ... 
-  preparing 'rjdqa':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'rjdqa_0.1.0.tar.gz'
   
* installing *source* package 'rjdqa' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rjdqa'
    finding HTML links ... done
    plot.sa_dashboard                       html  
    sa_dashboard                            html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'RJDemetra':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/MLiberts/Documents/R/R-3.6.0/library/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error : package 'RJDemetra' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/MLiberts/Documents/R/R-3.6.0/library/rjdqa'
* restoring previous 'C:/Users/MLiberts/Documents/R/R-3.6.0/library/rjdqa'
Error: Failed to install 'rjdqa' from GitHub:
  (converted from warning) installation of package ‘C:/Users/MLiberts/AppData/Local/Temp/RtmpMlZozK/file133c435434a0/rjdqa_0.1.0.tar.gz’ had non-zero exit status
```

**Installation with `args` - fails**

```
> devtools::install_github("AQLT/rjdqa", args = "--no-multiarch")
Downloading GitHub repo AQLT/rjdqa@master
√  checking for file 'C:\Users\MLiberts\AppData\Local\Temp\RtmpMlZozK\remotes133c18fa1be2\AQLT-rjdqa-89659e9/DESCRIPTION' ... 
-  preparing 'rjdqa':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'rjdqa_0.1.0.tar.gz'
   
* installing *source* package 'rjdqa' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rjdqa'
    finding HTML links ... done
    plot.sa_dashboard                       html  
    sa_dashboard                            html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'RJDemetra':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/MLiberts/Documents/R/R-3.6.0/library/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error : package 'RJDemetra' could not be loaded
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/MLiberts/Documents/R/R-3.6.0/library/rjdqa'
* restoring previous 'C:/Users/MLiberts/Documents/R/R-3.6.0/library/rjdqa'
Error: Failed to install 'rjdqa' from GitHub:
  (converted from warning) installation of package ‘C:/Users/MLiberts/AppData/Local/Temp/RtmpMlZozK/file133c21773ac/rjdqa_0.1.0.tar.gz’ had non-zero exit status
```

**Installation with `INSTALL_opts` - works**

```
> devtools::install_github("AQLT/rjdqa", INSTALL_opts = "--no-multiarch")
Downloading GitHub repo AQLT/rjdqa@master
√  checking for file 'C:\Users\MLiberts\AppData\Local\Temp\RtmpMlZozK\remotes133c23c22fc\AQLT-rjdqa-89659e9/DESCRIPTION' ... 
-  preparing 'rjdqa':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'rjdqa_0.1.0.tar.gz'
   
* installing *source* package 'rjdqa' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'rjdqa'
    finding HTML links ... done
    plot.sa_dashboard                       html  
    sa_dashboard                            html  
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rjdqa)
```

**Comment by AQLT** [comment]
Wonderful! Thank you for the explanation. I removed the argument in the actual README because it is only needed if you have a specific installation. So you must have the same problem with `RJDemetra`?

**Comment by djhurio** [comment]
Yes, I confirm this is the same for the `rjdemetra`. Installation fails if the `INSTALL_opts = "--no-multiarch"` argument is not specified.

I would keep the `INSTALL_opts = "--no-multiarch"` argument for both packages.

**Comment by AQLT** [comment]
With the CRAN release you don't have a problem because you must install from the binary file: `install.packages("rjdqa", type = "source")` will also produce an error unless you add the argument `INSTALL_opts = "--no-multiarch"`. I created an installation manual with this instruction in `RJDemetra`: https://github.com/jdemetra/rjdemetra/wiki/Installation-manual.

**Comment by djhurio** [comment]
Great. I see there are two `RJDemetra` installation manuals now. Both should be integrated:
https://github.com/jdemetra/rjdemetra/wiki/Installation-manual
https://jdemetra.github.io/rjdemetra/articles/installation-manual.html

**Comment by AQLT** [comment]
Indeed for the moment there are two installation manuals. By the end of the day, I will remove the vignette (https://jdemetra.github.io/rjdemetra/articles/installation-manual.html) because you will now have an error loading the package if you don't have Java 8 or higher (so you won't have non explicit errors like `Error in .jcall("jdr/spec/x13/X13Spec", "Ljdr/spec/x13/X13Spec;", "of", : RcallMethod: cannot determine object class`). I will do it today .

**Comment by AQLT** [comment]
I've added the link to the installation manual in the README. Thanks.
